routes:
  - uri: /api/v1/*
    name: "protected-api"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream:
      type: roundrobin
      nodes:
        "demo-service:80": 1
    plugins:
      oauth:
        discovery: http://hydra:4444/.well-known/openid_configuration
        bearer_only: true
        realm: "ory-demo"
        introspection_endpoint: http://hydra:4445/admin/oauth2/introspect
        client_id: apisix-client
        client_secret: apisix-secret

  - uri: /public/*
    name: "public-api" 
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "demo-service:80": 1

#END
